# Generated by Django 5.0.2 on 2024-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('request_type', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('submit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
